include $(HOME)/LaTeX_templates/Makefile

TEX_DEPS += ../src/DWT/*
TEX_DEPS += ./graphics/*

#index.html:	$(HOME)/LaTeX_templates $(HOME)/bibs

$(HOME)/bibs:
	git clone git@github.com:vicente-gonzalez-ruiz/bibs.git $(HOME)/bibs
